from dataclasses import dataclass


SOIL_TYPES = (
    "alluvial",
    "black",
    "clay",
    "laterite",
    "loam",
    "red",
    "sandy_loam",
    "silty_loam",
)

REGION_STATE_MAP = {
    "north": (
        "Punjab",
        "Haryana",
        "Uttar Pradesh",
        "Uttarakhand",
        "Himachal Pradesh",
        "Jammu and Kashmir",
    ),
    "south": (
        "Tamil Nadu",
        "Kerala",
        "Karnataka",
        "Andhra Pradesh",
        "Telangana",
    ),
    "east": (
        "West Bengal",
        "Odisha",
        "Bihar",
        "Jharkhand",
        "Assam",
    ),
    "west": (
        "Maharashtra",
        "Gujarat",
        "Rajasthan",
        "Goa",
    ),
    "central": (
        "Madhya Pradesh",
        "Chhattisgarh",
    ),
    "coastal": (
        "Kerala",
        "Goa",
        "Odisha",
        "Andhra Pradesh",
        "Tamil Nadu",
    ),
    "hill": (
        "Himachal Pradesh",
        "Uttarakhand",
        "Sikkim",
        "Arunachal Pradesh",
        "Jammu and Kashmir",
    ),
    "plateau": (
        "Karnataka",
        "Telangana",
        "Maharashtra",
        "Jharkhand",
        "Chhattisgarh",
    ),
}

SEASON_OPTIONS = ("kharif", "rabi", "zaid", "perennial")
IRRIGATION_OPTIONS = ("rainfed", "canal", "drip", "sprinkler", "flood")
REGION_OPTIONS = tuple(REGION_STATE_MAP.keys())


@dataclass(frozen=True)
class CropProfile:
    crop: str
    nitrogen: tuple[float, float]
    phosphorus: tuple[float, float]
    potassium: tuple[float, float]
    temperature: tuple[float, float]
    humidity: tuple[float, float]
    soil_ph: tuple[float, float]
    rainfall: tuple[float, float]
    soil_moisture: tuple[float, float]
    organic_matter: tuple[float, float]
    sunlight_hours: tuple[float, float]
    altitude: tuple[float, float]
    soil_types: tuple[str, ...]
    regions: tuple[str, ...]
    seasons: tuple[str, ...]
    irrigation_methods: tuple[str, ...]
    base_fertilizer: str


def _profile(**kwargs: object) -> CropProfile:
    return CropProfile(**kwargs)


CROP_PROFILES: dict[str, CropProfile] = {
    "rice": _profile(
        crop="rice",
        nitrogen=(85, 130),
        phosphorus=(35, 60),
        potassium=(40, 85),
        temperature=(22, 34),
        humidity=(70, 95),
        soil_ph=(5.5, 7.0),
        rainfall=(1500, 2600),
        soil_moisture=(55, 85),
        organic_matter=(1.5, 3.5),
        sunlight_hours=(6.0, 9.0),
        altitude=(0, 800),
        soil_types=("alluvial", "clay", "silty_loam"),
        regions=("east", "south", "coastal"),
        seasons=("kharif", "perennial"),
        irrigation_methods=("flood", "canal"),
        base_fertilizer="Urea + DAP",
    ),
    "wheat": _profile(
        crop="wheat",
        nitrogen=(70, 120),
        phosphorus=(30, 55),
        potassium=(35, 70),
        temperature=(10, 24),
        humidity=(45, 70),
        soil_ph=(6.0, 7.8),
        rainfall=(400, 900),
        soil_moisture=(20, 45),
        organic_matter=(1.2, 2.8),
        sunlight_hours=(8.0, 11.0),
        altitude=(100, 1500),
        soil_types=("loam", "silty_loam", "alluvial"),
        regions=("north", "central", "plateau"),
        seasons=("rabi",),
        irrigation_methods=("canal", "sprinkler"),
        base_fertilizer="Urea + SSP",
    ),
    "maize": _profile(
        crop="maize",
        nitrogen=(60, 110),
        phosphorus=(25, 55),
        potassium=(35, 75),
        temperature=(18, 32),
        humidity=(45, 80),
        soil_ph=(5.8, 7.5),
        rainfall=(500, 1200),
        soil_moisture=(25, 55),
        organic_matter=(1.4, 3.0),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 1200),
        soil_types=("loam", "red", "sandy_loam"),
        regions=("north", "west", "central", "plateau"),
        seasons=("kharif", "zaid"),
        irrigation_methods=("canal", "drip", "sprinkler"),
        base_fertilizer="Balanced NPK 10:26:26",
    ),
    "sugarcane": _profile(
        crop="sugarcane",
        nitrogen=(90, 140),
        phosphorus=(35, 60),
        potassium=(50, 95),
        temperature=(20, 38),
        humidity=(60, 90),
        soil_ph=(6.0, 7.5),
        rainfall=(1200, 2400),
        soil_moisture=(45, 75),
        organic_matter=(1.8, 3.5),
        sunlight_hours=(8.0, 12.0),
        altitude=(0, 900),
        soil_types=("alluvial", "black", "loam"),
        regions=("west", "south", "coastal", "central"),
        seasons=("kharif", "perennial"),
        irrigation_methods=("canal", "drip", "flood"),
        base_fertilizer="Urea + MOP",
    ),
    "cotton": _profile(
        crop="cotton",
        nitrogen=(50, 90),
        phosphorus=(25, 50),
        potassium=(40, 80),
        temperature=(21, 35),
        humidity=(35, 70),
        soil_ph=(6.0, 8.0),
        rainfall=(450, 1200),
        soil_moisture=(20, 45),
        organic_matter=(1.0, 2.5),
        sunlight_hours=(9.0, 12.0),
        altitude=(0, 1000),
        soil_types=("black", "red", "loam"),
        regions=("west", "central", "south"),
        seasons=("kharif",),
        irrigation_methods=("drip", "sprinkler"),
        base_fertilizer="DAP + MOP",
    ),
    "jute": _profile(
        crop="jute",
        nitrogen=(70, 120),
        phosphorus=(30, 55),
        potassium=(40, 80),
        temperature=(24, 34),
        humidity=(75, 95),
        soil_ph=(6.0, 7.5),
        rainfall=(1500, 2800),
        soil_moisture=(55, 85),
        organic_matter=(1.8, 3.5),
        sunlight_hours=(7.0, 10.0),
        altitude=(0, 700),
        soil_types=("alluvial", "clay", "silty_loam"),
        regions=("east", "coastal"),
        seasons=("kharif",),
        irrigation_methods=("rainfed", "flood"),
        base_fertilizer="Urea + Potash",
    ),
    "chickpea": _profile(
        crop="chickpea",
        nitrogen=(20, 50),
        phosphorus=(35, 70),
        potassium=(30, 65),
        temperature=(10, 30),
        humidity=(30, 70),
        soil_ph=(6.0, 8.5),
        rainfall=(300, 700),
        soil_moisture=(15, 35),
        organic_matter=(1.0, 2.5),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 1200),
        soil_types=("loam", "sandy_loam", "black"),
        regions=("north", "central", "west"),
        seasons=("rabi",),
        irrigation_methods=("rainfed", "sprinkler"),
        base_fertilizer="DAP + Rhizobium inoculant",
    ),
    "pigeonpea": _profile(
        crop="pigeonpea",
        nitrogen=(30, 60),
        phosphorus=(30, 60),
        potassium=(30, 70),
        temperature=(20, 35),
        humidity=(40, 80),
        soil_ph=(6.0, 7.8),
        rainfall=(600, 1200),
        soil_moisture=(20, 40),
        organic_matter=(1.2, 2.8),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 1000),
        soil_types=("loam", "red", "black"),
        regions=("central", "west", "south", "plateau"),
        seasons=("kharif",),
        irrigation_methods=("rainfed", "drip"),
        base_fertilizer="DAP + FYM",
    ),
    "kidneybeans": _profile(
        crop="kidneybeans",
        nitrogen=(25, 55),
        phosphorus=(30, 60),
        potassium=(30, 70),
        temperature=(15, 28),
        humidity=(45, 80),
        soil_ph=(6.0, 7.5),
        rainfall=(350, 900),
        soil_moisture=(20, 40),
        organic_matter=(1.2, 2.5),
        sunlight_hours=(7.0, 10.0),
        altitude=(200, 1600),
        soil_types=("loam", "sandy_loam", "red"),
        regions=("north", "west", "central", "hill"),
        seasons=("rabi", "kharif"),
        irrigation_methods=("drip", "sprinkler"),
        base_fertilizer="DAP + MOP",
    ),
    "lentil": _profile(
        crop="lentil",
        nitrogen=(20, 45),
        phosphorus=(30, 60),
        potassium=(25, 55),
        temperature=(8, 25),
        humidity=(30, 70),
        soil_ph=(6.0, 8.0),
        rainfall=(250, 600),
        soil_moisture=(15, 35),
        organic_matter=(1.0, 2.5),
        sunlight_hours=(7.0, 10.0),
        altitude=(0, 1500),
        soil_types=("loam", "silty_loam", "sandy_loam"),
        regions=("north", "east", "central", "hill"),
        seasons=("rabi",),
        irrigation_methods=("rainfed", "sprinkler"),
        base_fertilizer="SSP + Compost",
    ),
    "mungbean": _profile(
        crop="mungbean",
        nitrogen=(20, 45),
        phosphorus=(30, 60),
        potassium=(25, 60),
        temperature=(20, 35),
        humidity=(45, 80),
        soil_ph=(6.0, 7.5),
        rainfall=(400, 1000),
        soil_moisture=(20, 45),
        organic_matter=(1.0, 2.5),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 1000),
        soil_types=("loam", "red", "sandy_loam"),
        regions=("west", "south", "central", "plateau"),
        seasons=("kharif", "zaid"),
        irrigation_methods=("drip", "rainfed"),
        base_fertilizer="Balanced NPK 12:32:16",
    ),
    "blackgram": _profile(
        crop="blackgram",
        nitrogen=(25, 50),
        phosphorus=(30, 60),
        potassium=(25, 60),
        temperature=(20, 35),
        humidity=(50, 85),
        soil_ph=(6.0, 7.5),
        rainfall=(450, 1000),
        soil_moisture=(20, 45),
        organic_matter=(1.2, 2.8),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 1000),
        soil_types=("loam", "black", "sandy_loam"),
        regions=("south", "east", "coastal"),
        seasons=("kharif",),
        irrigation_methods=("rainfed", "drip"),
        base_fertilizer="DAP + Micronutrient mix",
    ),
    "groundnut": _profile(
        crop="groundnut",
        nitrogen=(30, 60),
        phosphorus=(35, 65),
        potassium=(35, 70),
        temperature=(20, 30),
        humidity=(40, 70),
        soil_ph=(6.0, 7.5),
        rainfall=(500, 1100),
        soil_moisture=(15, 35),
        organic_matter=(1.0, 2.5),
        sunlight_hours=(9.0, 12.0),
        altitude=(0, 800),
        soil_types=("sandy_loam", "loam", "red"),
        regions=("south", "west", "coastal", "plateau"),
        seasons=("kharif", "zaid"),
        irrigation_methods=("drip", "sprinkler"),
        base_fertilizer="Gypsum + SSP",
    ),
    "banana": _profile(
        crop="banana",
        nitrogen=(80, 140),
        phosphorus=(40, 80),
        potassium=(70, 130),
        temperature=(24, 35),
        humidity=(75, 95),
        soil_ph=(5.5, 7.0),
        rainfall=(1200, 2500),
        soil_moisture=(45, 75),
        organic_matter=(2.0, 4.0),
        sunlight_hours=(8.0, 11.0),
        altitude=(0, 900),
        soil_types=("alluvial", "loam", "black"),
        regions=("south", "coastal", "east"),
        seasons=("perennial", "kharif"),
        irrigation_methods=("drip", "flood"),
        base_fertilizer="NPK 12:12:17 + MOP",
    ),
    "potato": _profile(
        crop="potato",
        nitrogen=(60, 110),
        phosphorus=(35, 70),
        potassium=(60, 120),
        temperature=(12, 25),
        humidity=(55, 85),
        soil_ph=(5.0, 6.5),
        rainfall=(500, 1000),
        soil_moisture=(30, 60),
        organic_matter=(1.5, 3.0),
        sunlight_hours=(6.0, 9.0),
        altitude=(500, 2500),
        soil_types=("loam", "sandy_loam", "silty_loam"),
        regions=("north", "hill", "central"),
        seasons=("rabi",),
        irrigation_methods=("sprinkler", "drip"),
        base_fertilizer="NPK 13:13:21 + Potash",
    ),
    "apple": _profile(
        crop="apple",
        nitrogen=(40, 80),
        phosphorus=(25, 55),
        potassium=(40, 90),
        temperature=(4, 24),
        humidity=(50, 80),
        soil_ph=(5.5, 6.8),
        rainfall=(600, 1600),
        soil_moisture=(30, 60),
        organic_matter=(2.0, 4.5),
        sunlight_hours=(6.0, 9.0),
        altitude=(1200, 3000),
        soil_types=("loam", "sandy_loam", "silty_loam"),
        regions=("hill", "north"),
        seasons=("rabi", "perennial"),
        irrigation_methods=("drip", "sprinkler"),
        base_fertilizer="Calcium nitrate + MOP",
    ),
}
